# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD - Push to Prod

on:
  push:
    branches: [main]

jobs:
  push-to-prod:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [6.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Push to Prod
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: phansiri.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
